version: '3'
services:
  postgres:
    image: postgres:9.6.10
    environment:
      - POSTGRES_DB=communicator
    expose:
      - "5432"
  communicator:
    build: .
    links:
      - postgres:postgres
    environment:
      - SPRING.JPA.PROPERTIES.HIBERNATE.DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING.DATASOURCE.URL=jdbc:postgresql://postgres:5432/communicator
      - SPRING.DATASOURCE.USERNAME=postgres
      - SPRING.DATASOURCE.PASSWORD=postgres
      - SPRING.DATASOURCE.DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING.JPA.HIBERNATE.DDL-AUTO=update
    expose:
      - 8080
    ports:
      - "8080:8080"

